### ISSUE TITLE
ParquetJobs+ Athena not returning any data.

### ISSUE THREAD

**Issue by igalonso** [imjustdavid/workshop-ServerlessAnalytics#3]
After reviewing the job twice and running two times as well, I don't get any data from the parquet jobs.

![screen shot 2018-03-19 at 12 52 00 pm](https://user-images.githubusercontent.com/1102373/37594021-59e717c8-2b74-11e8-9f4d-38a4fc80ddc4.png)

**Comment by imjustdavid** [comment]
Fixed.
Parquet Crawler known issue: 
Include path must be: `s3://<workshop-bucket>/nyc-tlc-parquet/all` (without the trailing forward slash)
instead of: `s3://<workshop-bucket>/nyc-tlc-parquet/all/`

**Comment by igalonso** [comment]
Hey,

I tried your suggestion and I think it's not a problem of the crawler but the job. I don't get files bigger than a few bytes in the /nyc-tlc-parquet/all

![image](https://user-images.githubusercontent.com/1102373/37657158-7e173a16-2c4a-11e8-9dc8-e7f8f45820be.png)

**Comment by igalonso** [comment]
Can you paste here your own code of these jobs to see if there is any difference?

**Comment by igalonso** [comment]
Under:

> Now that you have a Parquet-formatted object on S3, create a new crawler to catalog the table just created:
> 
> Name: nyc-tlc-trip-record-data-parquet
> Data store: S3
> Crawl data in: Specified path in my account
> Include path: s3://<workshop-bucket>/nyc-tlc-parquet/all
> IAM role: DefaultAWSGlueServiceRole
> Frequency: Run on demand
> Add database: nyc-tlc-parquet

I think it should be s3://<workshop-bucket>/data/nyc-tlc-parquet/all

Otherwise, this path leads to a non created folder

**Comment by igalonso** [comment]
done! / required in the first crawler
